metrics:
  enabled: true
cr:
  create: true
  namespace: istio-system
  spec:
    auth:
      strategy: anonymous
    external_services:
      prometheus:
        url: kube-prometheus-stack-prometheus.monitoring.svc.cluster.local