metrics:
  enabled: true
cr:
  create: true
  namespace: istio-system
  spec:
    auth:
      strategy: anonymous
    external_services:
      prometheus:
        url: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
      grafana:
        enabled: true
        auth:
          type: bearer
          token: secret:kiali-grafana-secret:password
        in_cluster_url: http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local
        url: http://grafana.minikube.local