apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  sourceRepos:
    - "*"
  destinations:
    - namespace: "nginx"
      server: https://kubernetes.default.svc
    - namespace: "redis"
      server: https://kubernetes.default.svc
    - namespace: "postgresql"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"