apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform-project
  namespace: argocd
spec:
  description: Platform GitOps Project

  sourceRepos:
    - '*'

  destinations:
    - namespace: dev
      server: https://kubernetes.default.svc
    - namespace: test
      server: https://kubernetes.default.svc
    - namespace: prod
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'