apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: 'nginx'    
spec:
  project: platform
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: nginx
    targetRevision: 23.0.2
    helm:
      values: |
        replicaCount: 2
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx
  syncPolicy:
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
      - ServerSideApply=true