apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: 'postgresql'    
spec:
  project: platform
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 18.6.1
  destination:
    server: https://kubernetes.default.svc
    namespace: postgresql
  syncPolicy:
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
      - ServerSideApply=true