apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-app
  namespace: argocd
spec:
  project: platform-project

  source:
    repoURL: https://github.com/cyberforge33/platform-gitops.git
    targetRevision: develop
    path: apps/dev/workloads

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true