apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../argo-apps

patches:
  - path: ./patch-cluster-mgmt-appset.yaml
    target:
      kind: ApplicationSet
      name: cluster-mgmt
