apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: application-mgmt
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements: []
  template:
    metadata:
      name: '{{lower .name}}'
      labels:
        app.kubernetes.io/partof: "{{lower .name}}"
    spec:
      project: default
      source:
        repoURL: "{{.chartRepo}}"        
        chart: "{{.chart}}"
        targetRevision: "{{.chartVersion}}"
        helm:
          valueFiles:
            - "{{.valueFiles}}"
      destination:
        server: "{{.url}}"
        namespace: "{{.namespace}}"
      syncPolicy:
        syncOptions:
          - PruneLast=true
          - CreateNamespace=true          
        automated:
          prune: true
          selfHeal: true
