apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-mgmt
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements: []
  template:
    metadata:
      name: '{{lower .name}}'
      labels:
        app.kubernetes.io/partof: "{{lower .name}}"
    spec:
      project: default
      sources:
        - repoURL: "{{.chartRepo}}"        
          chart: "{{.chart}}"
          targetRevision: "{{.chartVersion}}"
          helm:
            valueFiles:
              - "$customvalues/{{.valueFiles}}"
        - repoURL: "{{.githubRepo}}"
          targetRevision: "{{.targetRevision}}"
          ref: customvalues
      destination:
        server: "{{.url}}"
        namespace: "{{.namespace}}"
      syncPolicy:
        syncOptions:
          - PruneLast=true
          - CreateNamespace=true          
          - ServerSideApply=true
        automated:
          prune: true
          selfHeal: true
