apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istio-gateways
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - env: dev
        path: overlays/dev/gateways
        targetRevision: HEAD
        server: https://kubernetes.default.svc
  template:
    metadata:
      name: 'istio-gateways-{{.env}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/cyberforge33/istio-config.git
        targetRevision: '{{.targetRevision}}'
        path: '{{.path}}'
      destination:
        server: '{{.server}}'
        namespace: isito-system
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
          - ServerSideApply=true
        automated:
          prune: true
          selfHeal: true
