apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./cluster-mgmt-appset.yaml
  - ./istio-gateways-appset.yaml
  - ./istio-traffic-mgmt-appset.yaml
  - ./monitoring-appset.yaml
