apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/cyberforge33/monitoring-config.git
    targetRevision: HEAD
    path: overlays/dev
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true      
      - PruneLast=true
    automated:
      prune: true
      selfHeal: true
